#!/bin/bash
set -euo pipefail

# Full bootstrap guide — checks prerequisites and prints the step-by-step
# workflow for Phase 2A (Magisk module on GrapheneOS via avbroot).
#
# Usage:
#   ./aosp/scripts/bootstrap.sh

echo "=== Urbit Mobile — Phase 2A Bootstrap ==="
echo ""
echo "Checking prerequisites..."
echo ""

MISSING=0

check_cmd() {
    if command -v "$1" &>/dev/null; then
        echo "  [ok] $1"
    else
        echo "  [!!] $1 — install: $2"
        MISSING=1
    fi
}

check_cmd "adb"     "brew install android-platform-tools"
check_cmd "avbroot" "download from https://github.com/chenxiaolong/avbroot/releases"
check_cmd "zip"     "should be pre-installed on macOS"

echo ""
if [ $MISSING -eq 1 ]; then
    echo "Install the missing tools above, then re-run this script."
    echo ""
    echo "NOTE: avbroot is NOT on crates.io. Download the binary from GitHub:"
    echo "  https://github.com/chenxiaolong/avbroot/releases"
    echo "  For macOS: universal-apple-darwin.zip"
    echo "  Extract and place in your PATH (e.g., ~/bin/avbroot)"
    exit 1
fi
echo "All prerequisites installed."
echo ""
echo "================================================================"
echo ""
echo "PHASE 2A DEPLOYMENT — Step by step"
echo ""
echo "  This workflow flashes stock GrapheneOS first, then layers"
echo "  Magisk-patched images on top. Tested on Pixel 8 Pro (husky)."
echo ""
echo "  WARNING: Step 5 WIPES the device. Backup your pier first!"
echo ""
echo "================================================================"
echo ""
echo "STEP 1: Backup your pier (do this FIRST — bootloader unlock wipes everything)"
echo ""
echo "  ./aosp/scripts/backup-pier.sh pier-backup"
echo "  ls -la pier-backup/urbit-pier/.urb/chk/   # verify checkpoint"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 2: Generate signing keys (one-time)"
echo ""
echo "  ./aosp/avbroot/setup-keys.sh keys"
echo "  # You'll be prompted for a passphrase — remember it!"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 3: Download three files"
echo ""
echo "  GrapheneOS OTA for husky (Pixel 8 Pro):"
echo "    https://grapheneos.org/releases"
echo "    Download: husky-ota_update-YYYY.MM.DD.HH.zip"
echo ""
echo "  GrapheneOS factory image (same build number):"
echo "    Download: husky-install-BUILDNUMBER.zip"
echo ""
echo "  Magisk APK (latest stable):"
echo "    https://github.com/topjohnwu/Magisk/releases"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 4: Patch OTA with Magisk + extract images"
echo ""
echo "  ./aosp/avbroot/patch-ota.sh <ota.zip> <Magisk-vXX.X.apk>"
echo ""
echo "  # Then extract patched images for fastboot:"
echo "  mkdir -p extracted"
echo "  avbroot ota extract \\"
echo "      --input <ota-magisk.zip> \\"
echo "      --directory extracted \\"
echo "      --fastboot"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 5: Unlock bootloader + flash stock GrapheneOS"
echo ""
echo "  On phone: Settings → System → Developer options → OEM unlocking (enable)"
echo ""
echo "  adb reboot bootloader"
echo "  fastboot flashing unlock"
echo "  # Confirm on phone"
echo ""
echo "  # Extract and flash factory image:"
echo "  unzip husky-install-*.zip"
echo "  cd husky-install-*/"
echo "  ./flash-all.sh"
echo "  # Wait for reboot into stock GrapheneOS"
echo "  cd .."
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 6: Flash Magisk-patched images on top"
echo ""
echo "  # Re-enable USB debugging on phone first"
echo "  # Settings → System → Developer options → USB debugging"
echo ""
echo "  adb reboot bootloader"
echo "  ANDROID_PRODUCT_OUT=extracted fastboot flashall --skip-reboot"
echo "  fastboot erase avb_custom_key"
echo "  fastboot flash avb_custom_key keys/avb_pkmd.bin"
echo "  fastboot reboot"
echo ""
echo "  # Phone will show 'device is corrupt' warning — this is expected."
echo "  # Select 'boot anyway'."
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 7: Set up Magisk"
echo ""
echo "  After phone boots into GrapheneOS:"
echo "  1. Complete initial setup (skip most, connect to WiFi)"
echo "  2. Re-enable USB debugging"
echo "  3. Open the Magisk app (pre-installed by avbroot)"
echo "  4. Let Magisk finish setup and reboot (may need 2 reboots)"
echo "  5. Verify root: adb shell su -c id"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 8: Build and install the vere module"
echo ""
echo "  # Include vere binary in the module (recommended)"
echo "  cp /path/to/urbit-patched aosp/magisk-module/common/urbit"
echo ""
echo "  # Build module zip"
echo "  ./aosp/scripts/build-module.sh"
echo ""
echo "  # Push to phone"
echo "  adb push urbit-vere-module.zip /sdcard/Download/"
echo ""
echo "  # Install: Magisk app → Modules → Install from storage"
echo "  # Select urbit-vere-module.zip from Downloads"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 9: Restore your pier"
echo ""
echo "  ./aosp/scripts/restore-pier.sh pier-backup"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 10: Reboot — vere starts automatically"
echo ""
echo "  adb reboot"
echo ""
echo "  # Verify after boot:"
echo "  adb shell \"su -c 'tail -20 /data/vere/urbit.log'\""
echo "  adb shell \"su -c 'cat /data/vere/monitor.log'\""
echo ""
echo "================================================================"
echo ""
echo "UPDATING GrapheneOS:"
echo ""
echo "  1. Download new OTA from grapheneos.org/releases"
echo "  2. ./aosp/avbroot/patch-ota.sh <new-ota.zip> <Magisk.apk>"
echo "  3. avbroot ota extract --input <new-ota-magisk.zip> --directory extracted --fastboot"
echo "  4. adb reboot bootloader"
echo "  5. ANDROID_PRODUCT_OUT=extracted fastboot flashall"
echo ""
echo "  Pier and Magisk modules survive updates."
echo ""
