#!/bin/bash
set -euo pipefail

# Full bootstrap guide — checks prerequisites and prints the step-by-step
# workflow for Phase 2 (Magisk module on GrapheneOS).
#
# Usage:
#   ./aosp/scripts/bootstrap.sh

echo "=== Urbit Mobile — Phase 2 Bootstrap ==="
echo ""
echo "Checking prerequisites..."
echo ""

MISSING=0

check_cmd() {
    if command -v "$1" &>/dev/null; then
        echo "  [ok] $1"
    else
        echo "  [!!] $1 — install: $2"
        MISSING=1
    fi
}

check_cmd "adb"     "brew install android-platform-tools"
check_cmd "avbroot" "cargo install avbroot"
check_cmd "zip"     "should be pre-installed on macOS"

echo ""
if [ $MISSING -eq 1 ]; then
    echo "Install the missing tools above, then re-run this script."
    exit 1
fi
echo "All prerequisites installed."
echo ""
echo "================================================================"
echo ""
echo "PHASE 2 DEPLOYMENT — Step by step"
echo ""
echo "================================================================"
echo ""
echo "STEP 1: Backup your pier (do this FIRST — bootloader unlock wipes everything)"
echo ""
echo "  ./aosp/scripts/backup-pier.sh pier-backup"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 2: Generate signing keys (one-time)"
echo ""
echo "  ./aosp/avbroot/setup-keys.sh keys"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 3: Download GrapheneOS OTA + Magisk"
echo ""
echo "  GrapheneOS OTA for husky (Pixel 8 Pro):"
echo "    https://grapheneos.org/releases"
echo "    Download the 'husky-ota_update-YYYY.MM.DD.HH.zip' file"
echo ""
echo "  Magisk APK (latest stable):"
echo "    https://github.com/topjohnwu/Magisk/releases"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 4: Patch the OTA with Magisk"
echo ""
echo "  ./aosp/avbroot/patch-ota.sh <ota.zip> <Magisk-vXX.X.apk>"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 5: Unlock bootloader (WARNING: this WIPES the device)"
echo ""
echo "  On phone: Settings -> System -> Developer options -> OEM unlocking (enable)"
echo "  Then:"
echo "    adb reboot bootloader"
echo "    fastboot flashing unlock"
echo "    # Follow on-screen prompts to confirm"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 6: Flash your AVB public key"
echo ""
echo "  fastboot flash avb_custom_key keys/avb_pkmd.bin"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 7: Flash the patched OTA"
echo ""
echo "  fastboot reboot recovery"
echo "  # On phone: select 'Apply update from ADB'"
echo "  adb sideload <ota-magisk.zip>"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 8: Relock bootloader"
echo ""
echo "  adb reboot bootloader"
echo "  fastboot flashing lock"
echo "  # IMPORTANT: Keep OEM unlocking ENABLED in developer options"
echo "  #            after boot, in case you need to re-unlock later"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 9: Set up Magisk"
echo ""
echo "  After phone boots into GrapheneOS:"
echo "  1. Complete initial setup (skip most, connect to WiFi)"
echo "  2. Open the Magisk app (it's pre-installed by avbroot)"
echo "  3. If Magisk asks to 'complete installation', let it and reboot"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 10: Build and install the vere module"
echo ""
echo "  # Optional: include vere binary in the module"
echo "  cp /path/to/urbit-patched aosp/magisk-module/common/urbit"
echo ""
echo "  # Build module zip"
echo "  ./aosp/scripts/build-module.sh"
echo ""
echo "  # Push to phone"
echo "  adb push urbit-vere-module.zip /sdcard/Download/"
echo ""
echo "  # Install: Magisk app -> Modules -> Install from storage"
echo "  # Select urbit-vere-module.zip from Downloads"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 11: Restore your pier"
echo ""
echo "  ./aosp/scripts/restore-pier.sh pier-backup"
echo ""
echo "----------------------------------------------------------------"
echo ""
echo "STEP 12: Reboot — vere starts automatically"
echo ""
echo "  adb reboot"
echo ""
echo "  Check status:"
echo "    adb shell cat /data/vere/urbit.log"
echo "    adb shell cat /data/vere/monitor.log"
echo ""
echo "================================================================"
echo ""
echo "After deployment, for each new GrapheneOS update:"
echo "  1. Download the new OTA from grapheneos.org/releases"
echo "  2. ./aosp/avbroot/patch-ota.sh <new-ota.zip> <Magisk.apk>"
echo "  3. adb sideload <new-ota-magisk.zip>"
echo "  (Pier and Magisk modules survive OTA updates)"
echo ""
